//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamTrackerSqlServerMvc.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserType { get; set; }
        public string Status { get; set; }
        public string InterviewStatus { get; set; }
        public string ReportingTo { get; set; }
        public string Mobile { get; set; }
    }
}
